import { NextRequest, NextResponse } from 'next/server';
import { Base64 } from 'js-base64';

export async function POST(req: NextRequest) {
    try {
        const { repoName, githubToken, code } = await req.json();

        if (!repoName || !githubToken || !code) {
            return NextResponse.json({ error: 'Missing required fields: repoName, githubToken, and code' }, { status: 400 });
        }

        // 1. Create a new repository
        const createRepoResponse = await fetch('https://api.github.com/user/repos', {
            method: 'POST',
            headers: {
                'Authorization': `token ${githubToken}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                name: repoName,
                description: 'Generated by Algorythm AI',
                private: false, // Or true, depending on desired default
            }),
        });

        const repoData = await createRepoResponse.json();

        if (!createRepoResponse.ok) {
            throw new Error(`Failed to create repository: ${repoData.message || 'Unknown error'}`);
        }

        const owner = repoData.owner.login;
        const repo = repoData.name;

        // 2. Create the file in the new repository
        const contentEncoded = Base64.encode(code);

        const createFileResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/src/App.tsx`, {
            method: 'PUT',
            headers: {
                'Authorization': `token ${githubToken}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                message: 'Initial commit: Add generated dApp code',
                content: contentEncoded,
            }),
        });

        if (!createFileResponse.ok) {
            // If file creation fails, we might want to clean up by deleting the repo
            // For now, we'll just throw the error.
            const fileErrorData = await createFileResponse.json();
            throw new Error(`Failed to create file in repository: ${fileErrorData.message || 'Unknown error'}`);
        }

        return NextResponse.json({
            message: 'Repository created and code synced successfully!',
            repoUrl: repoData.html_url,
        }, { status: 201 });

    } catch (error: any) {
        console.error('GitHub Sync Error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
