
export const firebaseConfig = {
  apiKey: "REPLACE_ME_WITH_YOUR_FIREBASE_API_KEY",
  authDomain: "REPLACE_ME_WITH_YOUR_FIREBASE_AUTH_DOMAIN",
  projectId: "REPLACE_ME_WITH_YOUR_FIREBASE_PROJECT_ID",
  storageBucket: "REPLACE_ME_WITH_YOUR_FIREBASE_STORAGE_BUCKET",
  messagingSenderId: "REPLACE_ME_WITH_YOUR_FIREBASE_MESSAGING_SENDER_ID",
  appId: "REPLACE_ME_WITH_YOUR_FIREBASE_APP_ID",
  measurementId: "REPLACE_ME_WITH_YOUR_FIREBASE_MEASUREMENT_ID",
};
